version: '3.8'

services:
  api:
    build: .
    container_name: user-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - ./app:/app/app
    networks:
      - user-network

  mongodb:
    image: mongo:7.0
    container_name: user-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - user-network

volumes:
  mongodb_data:

networks:
  user-network:
    driver: bridge